/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

/**
 *
 * @author angel
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        categoriasbtn = new javax.swing.JButton();
        GestProyTxt = new javax.swing.JLabel();
        comprabtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        subCategoriasbtn = new javax.swing.JButton();
        existenciasbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        salidabtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 295, -1, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        categoriasbtn.setBackground(new java.awt.Color(153, 153, 255));
        categoriasbtn.setForeground(new java.awt.Color(204, 255, 255));
        categoriasbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/igu/registro.png"))); // NOI18N
        categoriasbtn.setBorder(null);
        categoriasbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categoriasbtnMouseClicked(evt);
            }
        });
        categoriasbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoriasbtnActionPerformed(evt);
            }
        });

        GestProyTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        GestProyTxt.setForeground(new java.awt.Color(0, 0, 0));
        GestProyTxt.setText("CATEGORÍAS ");

        comprabtn.setBackground(new java.awt.Color(153, 153, 255));
        comprabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/igu/compra.png"))); // NOI18N

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PEDIDOS DE COMPRA");

        subCategoriasbtn.setBackground(new java.awt.Color(153, 153, 255));
        subCategoriasbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/igu/subregistro.png"))); // NOI18N
        subCategoriasbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subCategoriasbtnActionPerformed(evt);
            }
        });

        existenciasbtn.setBackground(new java.awt.Color(153, 153, 255));
        existenciasbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/igu/existencia.png"))); // NOI18N
        existenciasbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existenciasbtnActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("EXISTENCIAS");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("INFORMES");

        salidabtn.setBackground(new java.awt.Color(255, 102, 102));
        salidabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/igu/salida.png"))); // NOI18N
        salidabtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salidabtnMouseClicked(evt);
            }
        });
        salidabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salidabtnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("SUBCATEGORÍAS ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2)
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addGap(164, 164, 164))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(comprabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(276, 276, 276))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(GestProyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(168, 168, 168)))
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(categoriasbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(salidabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(existenciasbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(143, 143, 143)
                                        .addComponent(subCategoriasbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(salidabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subCategoriasbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(categoriasbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(GestProyTxt)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(comprabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(existenciasbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel4)))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-8, 0, 810, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoriasbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoriasbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoriasbtnActionPerformed

    private void existenciasbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existenciasbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_existenciasbtnActionPerformed

    private void categoriasbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categoriasbtnMouseClicked
        
        Productos prd = new Productos();
        prd.setVisible(true);
        dispose();
        
        
    }//GEN-LAST:event_categoriasbtnMouseClicked

    private void salidabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salidabtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salidabtnActionPerformed

    private void salidabtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidabtnMouseClicked
        
        Pantalla P = new Pantalla();
        P.setVisible(true);
        dispose();
    }//GEN-LAST:event_salidabtnMouseClicked

    private void subCategoriasbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subCategoriasbtnActionPerformed
        subCategorias subC = new subCategorias();
        subC.setVisible(true);
        dispose();
    }//GEN-LAST:event_subCategoriasbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GestProyTxt;
    private javax.swing.JButton categoriasbtn;
    private javax.swing.JButton comprabtn;
    private javax.swing.JButton existenciasbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton salidabtn;
    private javax.swing.JButton subCategoriasbtn;
    // End of variables declaration//GEN-END:variables
}
