/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package igu;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.List;
import proyectoalgoritmos.ProyectoAlgoritmos;

/**
 * @date 18/10/24
 * @author angelo chamalé
 */
public class Productos extends javax.swing.JFrame {

    // Se inicializa el modelo de la tabla directamente aqui
    DefaultTableModel model;
    private int idCounter = 1; // Contador para generar IDs automáticamente
    private int selectedRow = -1; // Para almacenar el índice de la fila seleccionada

    /**
     * Creates new form Productos
     */
    public Productos() {
        // Asignar el modelo de la tabla aquí en el constructor
        initComponents(); //inicializamos los componentes gráficos primero
        model = new DefaultTableModel(new Object[]{"ID", "Nombre", "Descripción"}, 0);
        Categoriastbl.setModel(model); // Asignar el modelo a la tabla después de su creación
        cargarCategoriasDesdeArchivo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        salidabtn = new javax.swing.JButton();
        nombreCategoriatxt = new javax.swing.JTextField();
        guardarbtn = new javax.swing.JButton();
        editarCategoriabtn = new javax.swing.JButton();
        eliminarbtn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Categoriastbl = new javax.swing.JTable();
        descrpCategoriastxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idCategoriatxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        salidabtn.setBackground(new java.awt.Color(255, 102, 102));
        salidabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/igu/salida.png"))); // NOI18N
        salidabtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salidabtnMouseClicked(evt);
            }
        });

        nombreCategoriatxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreCategoriatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreCategoriatxtActionPerformed(evt);
            }
        });

        guardarbtn.setBackground(new java.awt.Color(204, 204, 255));
        guardarbtn.setForeground(new java.awt.Color(204, 255, 255));
        guardarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/igu/agregar.png"))); // NOI18N
        guardarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarbtnActionPerformed(evt);
            }
        });

        editarCategoriabtn.setBackground(new java.awt.Color(204, 204, 255));
        editarCategoriabtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/igu/editar.png"))); // NOI18N
        editarCategoriabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCategoriabtnActionPerformed(evt);
            }
        });

        eliminarbtn.setBackground(new java.awt.Color(204, 204, 255));
        eliminarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/igu/eliminar.png"))); // NOI18N
        eliminarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarbtnActionPerformed(evt);
            }
        });

        Categoriastbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "DESCRIPCION"
            }
        ));
        Categoriastbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CategoriastblMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(Categoriastbl);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("NOMBRE:");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("DESCRIPCIÓN: ");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("CATEGORÍAS");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("GUARDAR");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("EDITAR CATEGORIA");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("ELIMINAR");

        idCategoriatxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idCategoriatxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(idCategoriatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel4)
                                        .addGap(87, 87, 87)
                                        .addComponent(jLabel6))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(guardarbtn)
                                        .addGap(118, 118, 118)
                                        .addComponent(editarCategoriabtn)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(106, 106, 106)
                                        .addComponent(jLabel7))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(95, 95, 95)
                                        .addComponent(eliminarbtn)))
                                .addGap(132, 132, 132)))
                        .addContainerGap(114, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(salidabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreCategoriatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(descrpCategoriastxt, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(138, 138, 138))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(salidabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCategoriatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descrpCategoriastxt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(idCategoriatxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editarCategoriabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eliminarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(guardarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cargarCategoriasDesdeArchivo() {
        List<String[]> categorias = ProyectoAlgoritmos.leerCategoriasDelArchivo();
        int maxId = 0;
        for (String[] categoria : categorias) {
            int id = Integer.parseInt(categoria[0]);
            model.addRow(new Object[]{categoria[0], categoria[1], categoria[2]});
            idCounter = Math.max(idCounter, Integer.parseInt(categoria[0]) + 1);
        }
    }

    private void salidabtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salidabtnMouseClicked

        menu M = new menu();
        M.setVisible(true);
        dispose();

    }//GEN-LAST:event_salidabtnMouseClicked

    private void nombreCategoriatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreCategoriatxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreCategoriatxtActionPerformed

    public void actionPerformed(ActionEvent e) {
        nuevaCategoria();
        guardarCategoria();
    }

    private void nuevaCategoria() {

    }

    private void guardarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarbtnActionPerformed
        // Verificar si hay datos en los campos de nombre y descripción
        if (nombreCategoriatxt.getText().isEmpty() || descrpCategoriastxt.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, complete todos los campos.");
        } else {
            String id = String.valueOf(idCounter++);
            idCategoriatxt.setText(id); // Mostrar el ID en el campo de texto
            String nombre = nombreCategoriatxt.getText();
            String descripcion = descrpCategoriastxt.getText();

            // Agregar a la tabla
            model.addRow(new Object[]{id, nombre, descripcion});

            // Guardar en el archivo de texto
            ProyectoAlgoritmos.guardarCategoriaEnArchivo(id, nombre, descripcion);
        }
    }//GEN-LAST:event_guardarbtnActionPerformed

    private void CategoriastblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CategoriastblMouseClicked

        // Obtener el índice de la fila seleccionada
        selectedRow = Categoriastbl.getSelectedRow();
        if (selectedRow != -1) {
            // Obtener el ID de la columna 0 de la fila seleccionada
            String id = model.getValueAt(selectedRow, 0).toString();
            // Rellenar los campos de texto con los datos de la fila seleccionada
            idCategoriatxt.setText(id); // Mostrar el ID en el campo de texto
            nombreCategoriatxt.setText(model.getValueAt(selectedRow, 1).toString());
            descrpCategoriastxt.setText(model.getValueAt(selectedRow, 2).toString());
        }
    }//GEN-LAST:event_CategoriastblMouseClicked

    private void editarCategoriabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCategoriabtnActionPerformed
        // Verificar si hay una fila seleccionada para editar
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila para editar.");
        } else {
            String nuevoNombre = nombreCategoriatxt.getText();
            String nuevaDescripcion = descrpCategoriastxt.getText();

            // Actualizar los datos en la tabla
            model.setValueAt(nuevoNombre, selectedRow, 1);
            model.setValueAt(nuevaDescripcion, selectedRow, 2);

            // Actualizar el archivo de texto
            actualizarArchivo();
            selectedRow = -1;
        }
    }//GEN-LAST:event_editarCategoriabtnActionPerformed

    private void eliminarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarbtnActionPerformed
        // Verificar si hay una fila seleccionada para eliminar
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione una fila para eliminar.");
        } else {
            // Eliminar de la tabla
            model.removeRow(selectedRow);

            // Actualizar el archivo de texto
            actualizarArchivo();
            selectedRow = -1;
        }
    }//GEN-LAST:event_eliminarbtnActionPerformed

    private void idCategoriatxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idCategoriatxtActionPerformed
        
    }//GEN-LAST:event_idCategoriatxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Categoriastbl;
    private javax.swing.JTextField descrpCategoriastxt;
    private javax.swing.JButton editarCategoriabtn;
    private javax.swing.JButton eliminarbtn;
    private javax.swing.JButton guardarbtn;
    private javax.swing.JTextField idCategoriatxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nombreCategoriatxt;
    private javax.swing.JButton salidabtn;
    // End of variables declaration//GEN-END:variables

    private void renumerarIds() {
        int rowCount = model.getRowCount();
        for (int i = 0; i < rowCount; i++) {
            model.setValueAt(i + 1, i, 0); // Asignar IDs secuenciale
        }
    }

    private void actualizarArchivo() {
        int rowCount = model.getRowCount();
        List<String[]> categorias = new java.util.ArrayList<>();

        for (int i = 0; i < rowCount; i++) {
            String id = model.getValueAt(i, 0).toString();
            String nombre = model.getValueAt(i, 1).toString();
            String descripcion = model.getValueAt(i, 2).toString();
            categorias.add(new String[]{id, nombre, descripcion});
        }

        // Sobrescribir el archivo con las categorías actualizadas
        ProyectoAlgoritmos.sobrescribirArchivoConCategorias(categorias);
    }

    private void guardarCategoria() {
        
    }
}
